package commands;

public enum ClientCommands {
    NUMBER_OF_PLAYERS,
    ADD_CARD_TO_HAND,
    DRAW_CARD_FROM_DECK,
    ADD_CARD_TO_SET,
    REMOVE_CARD_FROM_HAND,
    REMOVE_CARD_FROM_SET,
    DECK_CLICKED,
    PROMPT_PLAYER,
    PROMPT_PLAY_CARD,
    PROMPT_END_TURN,


}
