package commands;

public enum ServerCommands {
    SHOW_WAIT_FOR_OTHER_PLAYERS_VIEW,
    SHOW_MAIN_MENU_VIEW,
    SHOW_LOGIN_VIEW,
    SHOW_GAMEVIEW,
    WAIT_FOR_SETUP,
    CANNOT_JOIN,
    INIT_GAMEVIEW,
    EXIT,
    SETUP_GAME_GUI,
    ADD_CARD_TO_HAND,
    SET_MESSAGE_BOX,
    REMOVE_CARD_FROM_HAND,
    FILL_DECK,
    EMPTY_DECK,
}
